// stories-slider-51f03277da/src/svelte/StoriesSlider.svelte
<script>
  import { onMount, onDestroy } from 'svelte';
  import createStoriesSlider from '../stories-slider.esm.js';

  export let Swiper = undefined;
  export let EffectCube = undefined;
  export let enabled = true;
  export let autoplayDuration = 5000;
  export let onStoriesSlider = undefined;
  export let onSlidesIndexesChange = undefined;

  let elRef = null;
  let storiesSlider = null;

  onMount(() => {
    storiesSlider = createStoriesSlider(elRef, {
      Swiper,
      EffectCube,
      enabled,
      autoplayDuration,
      onSlidesIndexesChange,
    });
    if (onStoriesSlider) onStoriesSlider(storiesSlider);
    return () => {};
  }, []);
  onDestroy(() => {
    if (storiesSlider && storiesSlider.destroy) {
      storiesSlider.destroy();
    }
  });
</script>

<div class="stories-slider" bind:this={elRef} {...$$restProps}>
  <div class="swiper">
    <div class="swiper-wrapper"><slot /></div>
  </div>
</div>

// stories-slider-51f03277da/src/react/StoriesSlider.jsx
import React, { useEffect, useRef } from 'react';
import createStoriesSlider from '../stories-slider.esm.js';

export default function StoriesSlider(props) {
  const {
    Swiper,
    EffectCube,
    enabled = true,
    autoplayDuration = 5000,
    onStoriesSlider,
    onSlidesIndexesChange,
    children,
    ...rest
  } = props;

  const elRef = useRef(null);
  const storiesSlider = useRef(null);
  useEffect(() => {
    storiesSlider.current = createStoriesSlider(elRef.current, {
      Swiper,
      EffectCube,
      enabled,
      autoplayDuration,
      onSlidesIndexesChange,
    });
    if (onStoriesSlider) onStoriesSlider(storiesSlider.current);
    return () => {
      if (storiesSlider.current && storiesSlider.current.destroy) {
        storiesSlider.current.destroy();
      }
    };
  }, []);

  return (
    <div className="stories-slider" ref={elRef} {...rest}>
      <div className="swiper">
        <div className="swiper-wrapper">{children}</div>
      </div>
    </div>
  );
}
